// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNFHrus9eaMBL4YLpGI5rlYHeB8H0sGSM',
    appId: '1:613132978300:android:4efd6b633d2badaaf761f9',
    messagingSenderId: '613132978300',
    projectId: 'nashikkumbhsaathi',
    storageBucket: 'nashikkumbhsaathi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzNxM0rL4jZgcP_f-Xat7EHwgME6cRgc4',
    appId: '1:613132978300:ios:d7d795729511213bf761f9',
    messagingSenderId: '613132978300',
    projectId: 'nashikkumbhsaathi',
    storageBucket: 'nashikkumbhsaathi.firebasestorage.app',
    iosBundleId: 'com.sooubh.kumbhsaathi',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzIO0OkVw3p37JAKsx7ek3gqbLyRYVQqQ',
    appId: '1:613132978300:web:93a56be144d78e73f761f9',
    messagingSenderId: '613132978300',
    projectId: 'nashikkumbhsaathi',
    authDomain: 'nashikkumbhsaathi.firebaseapp.com',
    storageBucket: 'nashikkumbhsaathi.firebasestorage.app',
    measurementId: 'G-R7YNXEFKCQ',
  );
}
